pipeline {
    agent any
    tools { nodejs 'NodeJS-20' }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('FindX_UI') {
                    bat 'npm ci'
                }
            }
        }

        stage('Build') {
            steps {
                dir('FindX_UI') {
                    bat 'npm run build'
                }
            }
        }

        stage('Deploy / Run') {
            steps {
                dir('FindX_UI') {
                    bat '''
                        rmdir /S /Q C:\\deploy\\findx_ui
                        mkdir C:\\deploy\\findx_ui
                        xcopy /E /I /Y build C:\\deploy\\findx_ui
                    '''
                }
            }
        }
    }

    post {
        success { echo 'Build and deploy succeeded ✅' }
        failure { echo 'Build failed ❌' }
    }
}